### PR TITLE
Added testresources to maven

### PR DESCRIPTION
**Pull request by DanielBerge**
Reformatted file, that is why everything is changed. I only added line 73-77

```
<testResources>
    <testResource>
       <directory>${basedir}/assets</directory>
    </testResource>
</testResources>
```

### CODE REVIEW

**Comment by kh498** [comment]
That also mean that the `setup assets` can be removed

**Comment by DanielBerge** [comment]
> Can we use `resource` instead of `testResource`?
> This way we do not need to specify `working directory`
> 
> See the updated [Run with IntelliJ](https://github.com/inf112-v19/Blodige-roboter/wiki/Other_Run-with-IntelliJ) in the wiki

Sure, if that works. Can you fix, busy fixing merge conflicts in #56

**Comment by kh498** [comment]
Turns out you need both

**Comment by DanielBerge** [comment]
Fixes #78

**Pull request merged**
