### PR TITLE
56 proper gameroundlogic

### LINKED ISSUE #56: Proper gameround logic
should work with what @kh498 has done with #47

### PR DESCRIPTION
**Pull request by DanielBerge**
Fixes #56

### CODE REVIEW

**Comment by DanielBerge** [comment]
I will fix the documentation in IPlayer

**Comment by kh498** [comment]
It seems like teleporting back to backup is broken

```
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: Given location (7, -1) is out of bounds
	at no.uib.inf112.core.map.TiledMapHandler.setEntityOnBoard(TiledMapHandler.java:89)
	at no.uib.inf112.core.map.TiledMapHandler.update(TiledMapHandler.java:59)
	at no.uib.inf112.core.GameGraphics.render(GameGraphics.java:60)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by DanielBerge** [comment]
> It seems like teleporting back to backup is broken
> 
> ```
> Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: Given location (7, -1) is out of bounds
> 	at no.uib.inf112.core.map.TiledMapHandler.setEntityOnBoard(TiledMapHandler.java:89)
> 	at no.uib.inf112.core.map.TiledMapHandler.update(TiledMapHandler.java:59)
> 	at no.uib.inf112.core.GameGraphics.render(GameGraphics.java:60)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
> ```

Something you know how to fix?

**Comment by kh498** [comment]
Did it happen before the merge?

**Comment by DanielBerge** [comment]
> Did it happen before the merge?

Yes

**Comment by kh498** [comment]
I think it has to do with calling the wrong method in `PlayerHandler#endTurn()`. You need to call 
`card.getPlayer().moveRobot(card.getCard().getAction());` and not `card.getPlayer().getRobot().move(card.getCard().getAction());`

**Comment by DanielBerge** [comment]
> I think it has to do with calling the wrong method in `PlayerHandler#endTurn()`. You need to call
> `card.getPlayer().moveRobot(card.getCard().getAction());` and not `card.getPlayer().getRobot().move(card.getCard().getAction());`

Yup, that fixed it. Thanks!

**Comment by kh498** [comment]
You can hit enter a lot of times and the robot will fly around the map. maybe fix this by closing the ui untill the "animation" is finished?

**Comment by DanielBerge** [comment]
> You can hit enter a lot of times and the robot will fly around the map. maybe fix this by closing the ui untill the "animation" is finished?

Would be great, but i don't understad all the UI stuff

**Comment by kh498** [comment]
Replace `startTurn();` at the end of `PlayerHandler#endTurn` to be 
```java
GameGraphics.executorService
            .schedule(() -> Gdx.app.postRunnable(this::startTurn), 500 * (Player.MAX_PLAYER_CARDS + 2),
                      TimeUnit.MILLISECONDS);
```

This will wait till all the card have been used and then start a new round, 

oh and btw startTurn does not really `Activate lasers and so on` it just starts a new turn

**Comment by kh498** [comment]
Do not call `startTurn()`, call `GameGraphics.getRoboRally().round()` instead

**Comment by DanielBerge** [comment]
> Do not call `startTurn()`, call `GameGraphics.getRoboRally().round()` instead



> Do not call `startTurn()`, call `GameGraphics.getRoboRally().round()` instead

https://imgur.com/a/1vJWhFH

**Comment by kh498** [comment]
Add `() -> ` in front of `GameGraphics.getRoboRally().round()`. The whole thing should be something like

```java
GameGraphics.executorService
            .schedule(() -> Gdx.app.postRunnable(()->GameGraphics.getRoboRally().round()), 500 * (Player.MAX_PLAYER_CARDS + 2),
                      TimeUnit.MILLISECONDS);
```

**Pull request merged**
