### PR TITLE
44 walk of death

### LINKED ISSUE #44: The robot should die when walking of the map
Ref Robot:Line 70

### PR DESCRIPTION
**Pull request by kh498**
Fixes #44

### CODE REVIEW

**Comment by DanielBerge** [comment]
Any tests to check if this works?

**Comment by kh498** [comment]
It is hard to test if a robot is out of a map when `RoboRally.getCurrentMap()` is null

**Comment by DanielBerge** [comment]
Ahh, okey

**Comment by kh498** [comment]
I'll try and write some tests with Mockito

**Comment by DanielBerge** [comment]
> I'll try and write some tests with Mockito

Sweet

**Comment by kh498** [comment]
tests done @DanielBerge

**Pull request merged**
